#ifndef NGN_BINDING_INDICES_GLSL
#define NGN_BINDING_INDICES_GLSL

// Global 

#define SSBO_IDX_VIEWPORT_DATA					0
#define SSBO_IDX_SCENE_RENDER_ITEMS				1
#define SSBO_IDX_DRAW_RENDER_ITEM_INDICES		2

#endif